// src/components/layout/Navbar.vue
<template>
  <header>
    <nav
      :class="[
        'fixed top-0 left-0 w-full z-50 flex justify-between items-center px-6 md:px-12 transition-all duration-300',
        isScrolled
          ? 'bg-white/80 backdrop-blur-lg shadow-lg border-b border-gray-200 py-3'
          : 'bg-transparent py-5'
      ]"
    >
      <!-- Logo -->
      <div>
        <a href="/" class="flex items-center">
          <img
            :src="isScrolled ? reda_Logo_Blue : reda_Logo_Light"
            alt="ReDa Lab Logo"
            :class="[
              'transition-all duration-300 drop-shadow-md hover:scale-110',
              isScrolled ? 'h-14' : 'h-20'
            ]"
          />
        </a>
      </div>

      <!-- Nav Links -->
      <ul class="hidden md:flex items-center space-x-8">
        <li v-for="item in navItems" :key="item.name">
          <RouterLink
            :to="item.link"
            class="relative font-medium transition-all duration-300"
            :class="isScrolled ? 'text-gray-800' : 'text-white'"
          >
            {{ item.name }}

            <!-- Animated underline -->
            <span
              class="absolute left-0 -bottom-1 h-[2px] w-0 bg-yellow-400 transition-all duration-300 group-hover:w-full"
            ></span>
          </RouterLink>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script setup>
import { onMounted, onUnmounted, ref } from "vue";

defineOptions({
  name: "ComponentNavbar",
});

const isScrolled = ref(false);

const handleScroll = () => {
  isScrolled.value = window.scrollY > 50;
};

onMounted(() => {
  window.addEventListener("scroll", handleScroll);
});

onUnmounted(() => {
  window.removeEventListener("scroll", handleScroll);
});

const reda_Logo_Light = "/ReDa-Icon.png";
const reda_Logo_Blue = "/ReDa-Icon-Blue.png";

const navItems = [
  { name: "Home", link: "/" },
  { name: "About Us", link: "/AboutUs" },
  { name: "Projects", link: "/Projects" },
  { name: "Events", link: "/Events" },
  { name: "Board Members", link: "/Board-Members" },
  { name: "Contact", link: "/Contact" },
];
</script>

// src/layouts/navbar.tsx
import { Button } from "@/components/ui/button";
import { Menu, Search, X } from "lucide-react";
import { useEffect, useState } from "react";

const Navbar = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const navLinks = [
    { name: "Home", href: "/" },
    { name: "About Us", href: "/about" },
    { name: "Research Unit", href: "/research" },
    // { name: "Training Services", href: "/training-service" },
    { name: "Community", href: "/community" },
    { name: "Publication", href: "/publication" },
    { name: "Projects", href: "/projects" },
    { name: "Contact", href: "/contact" },
  ];

  return (
    <nav
      className={`fixed w-full z-50 transition-all duration-300 ${scrolled ? "bg-primary shadow-lg py-3" : "bg-transparent py-5"}`}
    >
      <div className="w-full px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center">
          {/* Logo */}
          <div className="flex items-center gap-2">
            <div className="w-auto h-10 rounded-full flex items-center justify-center text-[#0f3a5d] font-bold text-xl">
              <img
                src="/ReDa-Icon.png"
                alt="ReDA Lab Logo"
                className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
              />
            </div>
          </div>

          {/* Desktop Nav */}
          <div className="hidden md:flex items-center space-x-6">
            {navLinks.map((link) => (
              <a
                key={link.name}
                href={link.href}
                className="text-sm font-medium transition-colors text-white hover:text-yellow-400"
              >
                {link.name}
              </a>
            ))}
            <Button
              className="bg-white/10 p-2 rounded-full hover:bg-white/20 transition text-white"
            >
              <Search size={18} />
            </Button>
          </div>

          {/* Mobile Menu Button */}
          <div className="md:hidden flex items-center">
            <Button
              onClick={() => setIsOpen(!isOpen)}
              className={
                scrolled ? "bg-white text-primary" : "bg-primary text-white"
              }
            >
              {isOpen ? <X size={28} /> : <Menu size={28} />}
            </Button>
          </div>
        </div>
      </div>

      {/* Mobile Nav */}
      {isOpen && (
        <div
          className={`md:hidden bg-primary ${scrolled ? "bg-primary border-primary" : "bg-white border-white"} border-t  absolute w-full`}
        >
          <div className="px-4 pt-2 pb-6 space-y-2">
            {navLinks.map((link) => (
              <a
                key={link.name}
                href={link.href}
                className={`block px-3 py-3 text-base font-medium ${scrolled ? "text-white hover:bg-blue-800" : "text-primary hover:bg-blue-100"} rounded-md`}
                onClick={() => setIsOpen(false)}
              >
                {link.name}
              </a>
            ))}
          </div>
        </div>
      )}
    </nav>
  );
};

export default Navbar;
